Repository ASFHyP3/asf-stac, pull requests merged in 2022-12, with the labels that each got.

#110 remove ingest_items.py, update create_coherence_items.py to write to …
  collections/ingest_data.py
  collections/sentinel-1-global-coherence/create_coherence_items.py
Labels: bumpless

#113 increase db ec2 and storage resources
  apps/database/cloudformation.yml
Labels: bumpless

#112 set search path in configure-database-roles.sql
  configure-database-roles.sql
Labels: bumpless

#115 update polarizations summary for coherence collection
  collections/sentinel-1-global-coherence/sentinel-1-global-coherence.json
Labels: bumpless

#118 Exclude duplicate objects
  README.md
  collections/sentinel-1-global-coherence/create_coherence_items.py
  collections/sentinel-1-global-coherence/list-coherence-objects
Labels: bumpless

#121 Update Changelog for Release 0.2.0
  CHANGELOG.md
Labels: minor

#120 Release 0.2.0
  .github/workflows/tests.yml
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  apps/database/buildspec.yml
  apps/database/cloudformation.yml
  collections/sentinel-1-global-coherence/create_coherence_items.py
  collections/sentinel-1-global-coherence/list-coherence-objects
  collections/sentinel-1-global-coherence/sentinel-1-global-coherence.json
  configure-database-roles.sql
  convert_collection_to_ndjson.py
  data/france_urls.txt
  environment.yml
  ingest_data.py
  requirements-run-codebuild.txt
  requirements.txt
  src/coherence_stac.py
  tests/test_create_coherence_items.py
Labels: minor

#122 Fix path in README ingest steps
  README.md
Labels: bumpless

#126 Add collection for glo-30-hand data set
  apps/database/buildspec.yml
  collections/glo-30-hand/glo-30-hand.json
  convert_collection_to_ndjson.py
  convert_collections_to_ndjson.py
Labels: bumpless

#125 Create and ingest HAND dataset
  .github/workflows/tests.yml
  .gitignore
  Makefile
  README.md
  collections/glo-30-hand/create_hand_items.py
  collections/glo-30-hand/list-hand-objects
  collections/sentinel-1-global-coherence/create_coherence_items.py
  environment.yml
  lib/asf-stac-util/asf_stac_util/__init__.py
  lib/asf-stac-util/setup.py
  requirements.txt
  tests/test_asf_stac_util.py
  tests/test_create_coherence_items.py
  tests/test_create_hand_items.py
Labels: bumpless

#129 Add start and end datetimes for HAND items
  collections/glo-30-hand/create_hand_items.py
  tests/test_create_hand_items.py
Labels: bumpless

#130 Add STAC Browser URLs to README
  README.md
Labels: bumpless

#131 set temporal extent for glo-30-hand collection
  collections/glo-30-hand/glo-30-hand.json
Labels: bumpless

#133 Add Changelog entry for HAND dataset
  CHANGELOG.md
Labels: bumpless

#132 Release 0.3.0
  .github/workflows/tests.yml
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  apps/database/buildspec.yml
  collections/glo-30-hand/create_hand_items.py
  collections/glo-30-hand/glo-30-hand.json
  collections/glo-30-hand/list-hand-objects
  collections/sentinel-1-global-coherence/create_coherence_items.py
  convert_collection_to_ndjson.py
  convert_collections_to_ndjson.py
  environment.yml
  lib/asf-stac-util/asf_stac_util/__init__.py
  lib/asf-stac-util/setup.py
  requirements.txt
  tests/test_asf_stac_util.py
  tests/test_create_coherence_items.py
  tests/test_create_hand_items.py
Labels: minor

#134 Disable transaction endpoints for public API
  CHANGELOG.md
  Makefile
  README.md
  apps/api/src/api.py
Labels: patch

#140 Remove Filter extension
  apps/api/src/api.py
Labels: bumpless

#138 Release 0.3.1
  CHANGELOG.md
  Makefile
  README.md
  apps/api/src/api.py
  requirements-apps-api.txt
  requirements-run-codebuild.txt
  requirements.txt
Labels: patch

#154 Release 0.3.2
  CHANGELOG.md
  collections/glo-30-hand/create_hand_items.py
  requirements-run-codebuild.txt
  requirements.txt
  tests/test_create_hand_items.py
Labels: patch
